name: Automated Push to S3
on: 
  push:
    branches:
      - 'master'
      - 'cert'
      - 'prod'
    paths: 
      - 'scripts/productdata/**.csv'
      - 'scripts/productdata/**.txt'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs: 
      runner: ${{steps.step1.outputs.runner}}
      appEnv: ${{steps.step1.outputs.appEnv}}
    steps:
      - name: Check branch
        id: step1
        shell: bash
        run: |
          echo "Running on ${{github.ref_name}} branch"
          if [ ${{github.ref_name}} = "master" ]; then
            echo "::set-output name=runner::ubuntu-latest"
            echo "::set-output name=appEnv::devl"
          elif [ ${{github.ref_name}} = "cert" ]; then
            echo "::set-output name=runner::windows-latest"
            echo "::set-output name=appEnv::cert"
          else
            echo "::set-output name=runner::windows-2019"
            echo "::set-output name=appEnv::prod"
          fi

  pushToS3:
    needs: [setup]
    uses: ${{github.repository}}/.github/workflows/push-to-S3.yml@main
    with:
      Env: ${{needs.setup.outputs.appEnv}}
      Runner: ${{needs.setup.outputs.runner}}