name: Automated Build jar

on: 
  push:
    branches:
      - 'master'
      - 'cert'
      - 'prod'
      - 'test'
    paths: 
      - 'src/main/**'
      - 'project/**'
      - 'build.sbt'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs: 
      runner: ${{steps.step1.outputs.runner}}
      appEnv: ${{steps.step1.outputs.appEnv}}
    steps:
      - name: Set Env and Runner
        id: step1
        shell: bash
        run: |
          if [ ${{github.ref_name}} = "master" ]; then
            echo "::set-output name=runner::ubuntu-latest"
            echo "::set-output name=appEnv::devl"
          elif [ ${{github.ref_name}} = "cert" ]; then
            echo "::set-output name=runner::windows-latest"
            echo "::set-output name=appEnv::cert"
          else
            echo "::set-output name=runner::windows-2019"
            echo "::set-output name=appEnv::prod"
          fi
  buildJar:
    needs: [setup]
    uses: ./.github/workflows/build-jar.yml
    with:
      logLevel: info
      Env: ${{needs.setup.outputs.appEnv}}
      Runner: ${{needs.setup.outputs.runner}}

  runDatabricksJob:
    needs: [setup, buildJar]
    uses: ./.github/workflows/databricks-job.yml
    with:
      logLevel: info
      Env: ${{needs.setup.outputs.appEnv}}
      Runner: ${{needs.setup.outputs.Runner}}