name: Push to S3
on:
  workflow_dispatch:
    inputs:
      Env: 
        description: 'Select Env'
        required: true
        default: 'devl'
        type: choice
        options:
          - devl
          - cert
          - prod
      Runner:
        description: 'Select GHA Runner'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - windows-2019
  workflow_call:
    inputs:
      Env: 
        required: true
        type: string
      Runner:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{github.event.inputs.Runner}}
    steps:
      - run: echo "Environment - ${{github.event.inputs.Env}}"
      - run: echo "Runner OS - ${{runner.os}}"