name: Run AWS CLI

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute'
        required: true

jobs:
  runCommand:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo ${{inputs.command}}
          $command